# Generated by Django 5.2.14 on 2026-05-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(help_text='e.g. WHO-GMP, ISO 9001:2015', max_length=50)),
                ('icon', models.CharField(default='🏅', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured images appear larger in the gallery grid')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='PANAS Pharmaceutical', max_length=200)),
                ('company_short', models.CharField(default='PANAS Pharma', max_length=100)),
                ('tagline', models.CharField(default='Lighting the lamp for living a healthy life', max_length=300)),
                ('established_year', models.PositiveIntegerField(default=1995)),
                ('hero_heading', models.CharField(default='Lighting the Lamp for Living a Healthy Life', max_length=300)),
                ('hero_subtext', models.TextField(default='Panas Pharmaceutical P. Ltd. has been delivering safety and peace of mind through health care products manufactured under the highest international standards since 1995.')),
                ('announcement_text', models.TextField(default='Welcome to Panas Pharmaceuticals', help_text='Scrolling ticker text on top of the site')),
                ('phone_primary', models.CharField(default='(977) 81-403004', max_length=30)),
                ('phone_secondary', models.CharField(blank=True, default='081-523668', max_length=30)),
                ('email', models.EmailField(default='info@panaspharma.com', max_length=254)),
                ('website_url', models.URLField(blank=True, default='https://www.panaspharma.com')),
                ('address_line1', models.CharField(default='Janaki-6, Ganapur', max_length=200)),
                ('address_line2', models.CharField(default='Banke, Nepal', max_length=200)),
                ('google_maps_url', models.URLField(blank=True, default='https://maps.google.com/?q=Banke,Nepal')),
                ('about_short', models.TextField(default="From a humble beginning in Banke, Nepal, Panas Pharmaceuticals has grown into one of Nepal's most trusted names in healthcare manufacturing.")),
                ('about_full', models.TextField(default='Panas Pharmaceutical P. Ltd. was established with a clear and noble purpose — to make quality, affordable medicines accessible to every Nepali.')),
                ('mission', models.TextField(default='To manufacture and deliver high-quality, safe, and effective pharmaceutical products that improve the health and quality of life of the people of Nepal, at an affordable cost.')),
                ('vision', models.TextField(default='"To live healthy and enjoy life to the fullest every day." We envision a Nepal where every citizen has access to world-class healthcare products.')),
                ('values', models.TextField(default='Quality, Integrity, Innovation, and Community. We believe that business success and social responsibility go hand in hand.')),
                ('fiscal_year', models.CharField(default='2081/82', max_length=20)),
                ('copyright_text', models.CharField(default='Copyright 2006-2026 Panas Pharmaceuticals P. Ltd. All Rights Reserved.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
